/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi_sarpras;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class FProfil extends javax.swing.JFrame {

    /**
     * Creates new form FProfil
     */
    koneksi koneksi;
    Statement st;
    ResultSet rs;    
    String user_id=UserSession.getS_user();
    int id_level=UserSession.getS_level();
    String level_id=String.valueOf(id_level);
    public FProfil() {
        initComponents();
        koneksi=new koneksi();
        ShowName();
        Message.setNameClass("Profil");
    }
    public void ShowName(){        
        try{
            st=koneksi.con.createStatement();
            String sql="select NAMA_PETUGAS from tbl_petugas where KD_PETUGAS='"+user_id+"'";
            rs=st.executeQuery(sql);
            if(rs.next()){
                NamaPetugas.setText(rs.getString("NAMA_PETUGAS"));
                Nama.setText(rs.getString("NAMA_PETUGAS"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    public void UpdatePetugas(){
        try{            
         if(Nama.isEnabled()){
             if(!Nama.getText().isEmpty()){
                st=koneksi.con.createStatement();
                String sql="update tbl_petugas set NAMA_PETUGAS='"+Nama.getText()+"' where KD_PETUGAS='"+user_id+"'";
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "Nama Petugas Berhasil Di Perbaharui");
             }
             else{
                 JOptionPane.showMessageDialog(null, "Nama Tidak Boleh Kosong!");
             }             
         }    
         if(!Username.getText().isEmpty()){
             st=koneksi.con.createStatement();
             String sql="update tbl_petugas set USERNAME_PETUGAS='"+Username.getText()+"' where KD_PETUGAS='"+user_id+"'";
             st.executeUpdate(sql);
             JOptionPane.showMessageDialog(null, "Username Petugas Berhasil Di Perbaharui");
         }
         if(!NewPassword.getText().isEmpty()){
            st=koneksi.con.createStatement();
            String Check="select PASSWORD_PETUGAS from tbl_petugas where PASSWORD_PETUGAS='"+OldPassword.getText()+"' and KD_PETUGAS='"+user_id+"'";
            rs=st.executeQuery(Check);
            if(rs.next()){
                if(NewPassword.getText().equals(ConfirmPassword.getText())){
                    st=koneksi.con.createStatement();
                    String update_password="update tbl_petugas set PASSWORD_PETUGAS='"+NewPassword.getText()+"' where KD_PETUGAS='"+user_id+"'";
                    st.executeUpdate(update_password);
                    JOptionPane.showMessageDialog(null, "Password Berhasil Di Perbaharui");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Maaf Password Lama Anda Salah");
                NewPassword.setText("");
                OldPassword.setText("");
                ConfirmPassword.setText("");
            }            
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }                
    }
    public void Clear(){
        ShowName();
        Username.setText("");
        NewPassword.setText("");
        OldPassword.setText("");
        ConfirmPassword.setText("");
        CheckName.setSelected(false);
        Nama.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ConfirmPassword = new javax.swing.JPasswordField();
        NewPassword = new javax.swing.JPasswordField();
        OldPassword = new javax.swing.JPasswordField();
        Username = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        BSimpan = new javax.swing.JButton();
        BClose = new javax.swing.JButton();
        NamaPetugas = new javax.swing.JLabel();
        CheckName = new javax.swing.JCheckBox();
        alert = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Form Profil");

        jLabel2.setText("Nama");

        jLabel3.setText("Username");

        jLabel4.setText("Password Lama");

        jLabel5.setText("Password Baru");

        jLabel6.setText("Konfirmasi Password");

        Nama.setEnabled(false);

        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Save_16.png"))); // NOI18N
        BSimpan.setText("SAVE");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        BClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Close_Window_16.png"))); // NOI18N
        BClose.setText("CLOSE");
        BClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCloseActionPerformed(evt);
            }
        });

        CheckName.setText("Edit Nama");
        CheckName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckNameActionPerformed(evt);
            }
        });

        alert.setText("*Jika Hanya Ingin Mengedit Salah Satu Kosongkan Yang tidak Perlu Di Edit");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alert)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(NamaPetugas))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BSimpan)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                        .addComponent(BClose))
                                    .addComponent(Nama)
                                    .addComponent(Username)
                                    .addComponent(OldPassword)
                                    .addComponent(NewPassword)
                                    .addComponent(ConfirmPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CheckName))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(NamaPetugas))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(OldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(NewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(alert)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSimpan)
                    .addComponent(BClose))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckNameActionPerformed
        // TODO add your handling code here:
        if(CheckName.isSelected()){
            Nama.setEnabled(true);
        }else if(!CheckName.isSelected()){
            Nama.setEnabled(false);
        }
    }//GEN-LAST:event_CheckNameActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        int response=Message.getM_update();
        if(response==JOptionPane.YES_OPTION){
            UpdatePetugas();
            Clear();
        }
    }//GEN-LAST:event_BSimpanActionPerformed

    private void BCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCloseActionPerformed
        // TODO add your handling code here:
        new FUtama().show();
        this.dispose();
    }//GEN-LAST:event_BCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FProfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FProfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClose;
    private javax.swing.JButton BSimpan;
    private javax.swing.JCheckBox CheckName;
    private javax.swing.JPasswordField ConfirmPassword;
    private javax.swing.JTextField Nama;
    private javax.swing.JLabel NamaPetugas;
    private javax.swing.JPasswordField NewPassword;
    private javax.swing.JPasswordField OldPassword;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel alert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
